/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Requirement = IDL.Variant({
  'tiles' : IDL.Null,
  'interior' : IDL.Null,
  'other' : IDL.Null,
  'kitchen' : IDL.Null,
});
export const Time = IDL.Int;
export const Submission = IDL.Record({
  'name' : IDL.Text,
  'requirement' : Requirement,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'submitForm' : IDL.Func([IDL.Text, IDL.Text, Requirement, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Requirement = IDL.Variant({
    'tiles' : IDL.Null,
    'interior' : IDL.Null,
    'other' : IDL.Null,
    'kitchen' : IDL.Null,
  });
  const Time = IDL.Int;
  const Submission = IDL.Record({
    'name' : IDL.Text,
    'requirement' : Requirement,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'submitForm' : IDL.Func(
        [IDL.Text, IDL.Text, Requirement, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };